CREATE TABLE "sections" (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    user_id VARCHAR(255) NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    goal INTEGER NOT NULL
);